global:
  controlPlaneSecurityEnabled: true

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"

  trustDomain: "csm-fsa@istionodeagenttestproj4.iam.gserviceaccount.com"

  useMCP: false

nodeagent:
  enabled: true
  image: node-agent-k8s
  env:
    CA_PROVIDER: "GoogleCA"
    CA_ADDR: "istioca.googleapis.com:443"

